---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aitrkjwg/aikrok.com/
    - /bin/cp index.html styles.css script.js scene.js i18n.js icons.svg example-dashboard.svg robots.txt sitemap.xml llms.txt $DEPLOYPATH
    - /bin/sh -c 'grep -qs "AddCharset UTF-8 .txt" ${DEPLOYPATH}.htaccess || printf "\nAddCharset UTF-8 .txt\n" >> ${DEPLOYPATH}.htaccess'
